name: flutter_card
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - asset/images/r1.jpg
    - asset/images/r2.jpg
    - asset/images/r3.jpg
    - asset/images/r4.jpg
    - asset/images/r5.jpg
    - asset/images/r6.jpg
    - asset/images/r7.jpg
    - asset/images/r8.jpg
    - asset/images/r9.jpg
    - asset/images/r10.jpg
